dist: bionic
language: cpp
os:
  - linux
compiler:
  - clang

addons:
  apt:
      packages: ['docker-ce', 'postgresql-server-dev-11']

before_script:
  - docker version

script:
  - sh src/tools/pgindent/check-indent.sh
  - make docker-image
